[package]
name = "bcp-controller"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
bcp-core.workspace = true
bcp-proto.workspace = true
clap.workspace = true
prost.workspace = true
rusqlite.workspace = true
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio.workspace = true
